### ISSUE TITLE
Optimistic updates

### ISSUE THREAD

**Issue by lorensr** [haytko/apollo-link-watched-mutation#4]
It would be nice if this package worked with `optimisticResponse`s. Currently, my update functions aren't called until the response is received from the server.

**Comment by haytko** [comment]
Hey, I've thought about that too and agree that it sounds like a reasonable request. I'll follow along with that issue you referenced.

I think, in the best case scenario, our WatchedMutationLink would handle reverting any optimistic cache update as well. 

Otherwise, I think we would have to at least expose a way of being notified about mutation errors as well.

Thoughts ?

**Comment by lorensr** [comment]
> would handle reverting any optimistic cache update as well.

reverting = undoing the changes before running the update function again with the real result from the server? yes, it would be good to mirror the process that `apollo-client` currently uses for optimistic updates.

**Comment by haytko** [comment]
Hey @lorensr I just published a 0.2.0 that aims to support optimistic updates. 

Here's the way it should currently work:
- the associated callback is invoked immediately upon seeing an optimistic response
- any error for that mutation will trigger a reversion of the cache update from ☝️
- any success will trigger nothing since we already updated the cache optimistically.

Please give it a try and let me know if it works for your use cases.

**Comment by haytko** [comment]
@lindlof Thanks for testing, glad to hear that the functionality is there and sorry to hear the structure wasn't what was intended. (The optimistic response based off of context is structured a bit differently than a mutation's result so I need to transform it before invoking the callback.)

I've just published a 0.2.1 which takes this into account and should provide a consistent interface within the callback 👍
