### ISSUE TITLE
Cannot find module '@babel/runtime/core-js/get-iterator'

### ISSUE THREAD

**Issue by ralphchristianeclipse** [haytko/apollo-link-watched-mutation#5]
"apollo-link-watched-mutation": "^0.1.0",

with this version

and with this babel rc using quasar framework

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "loose": false,
        "useBuiltIns": "usage"
      }
    ],
    [
      "@babel/preset-stage-2",
      {
        "modules": false,
        "loose": false,
        "useBuiltIns": true,
        "decoratorsLegacy": true
      }
    ]
  ],
  "plugins": [
    [
      "@babel/transform-runtime",
      {
        "polyfill": false,
        "regenerator": false
      }
    ]
  ],
  "comments": false
}

```
quasar-cli

any ideas?

**Comment by haytko** [comment]
Hey @ralphchristianeclipse,

Ahh, the joys of babel. I haven't run into this exact scenario but from a brief google search it seemed like this was sometimes a false positive ?

These people seemed to be able to get around it by just deleting their node_modules an reinstalling.

https://github.com/miaolz123/vue-markdown/issues/18
https://github.com/wallabyjs/quokka/issues/150

Hopefully that helps, otherwise i'm not sure... I'd have to try and mimic your setup and give it a go.

**Comment by nothingismagick** [comment]
i think that it is a problem with beta.54 

Removing this works:

```
    [
      "@babel/plugin-transform-runtime", {
      "regenerator": false
    }
    ]
```

**Comment by haytko** [comment]
Huh, well, glad you got that figured out ! 

I'll go ahead and close this assuming you don't have anything else related ?

**Comment by nothingismagick** [comment]
but i am still hitting the error on build

**Comment by nothingismagick** [comment]
No I resolved it for dev by making sure that all my babel packages are using "7.0.0-beta.54"

WIN!!!

**Comment by haytko** [comment]
Oh, sorry for the misunderstanding.

Sounds like another entry in the annals of babel frustrations.

**Comment by nothingismagick** [comment]
its my weekly hobby. fighting with babel

**Comment by mesqueeb** [comment]
@nothingismagick I'm having this same problem today.

**Comment by dsignr** [comment]
This still happens if you are using an older version of `Vuex` and `graphql` plugins and libraries. In my case, the culprits were `vuex` , `apollo-upload-client` and `graphql-tag`. Once I updated them, everything was back to normal.

The reason you were able to solve it by creating a new project is probably the newer project contained updated libraries. Thanks for sharing your solution, otherwise I was deep down the rabbit hole!

**Comment by KaisNeffati** [comment]
Resolved by running 

`npm i --save-dev babel-loader@7.1.5
`
